version: '3'
services:
  php:
    container_name: php-fpm
    hostname: php-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    command: php-fpm
    depends_on:
      - database
    volumes:
      - ./:/app

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./docker/nginx/
      dockerfile: ./Dockerfile
    depends_on:
      - php
    ports:
      - "8000:80"

  database:
    container_name: database
    hostname: database
    build:
      context: ./docker/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: some-database
    ports:
      - "33060:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
